server:
  port: 8080
  servlet:    context-path: /
    encoding:      charset: utf-8
      enabled: true
      spring:  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp
        datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/parkdb?serverTimezone=Asia/Seoul
    username: park
    password: park1234
      jpa:    open-in-view: true
    hibernate:      ddl-auto: create
      naming:        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    
    # 콘솔에 출력되는 SQL문을 보기 좋게 만들어 줍니다.    
    show-sql: true
    properties:
      hibernate.format_sql: ture
      
  jackson:    serialization:      fail-on-empty-beans: false      
      
    
    